// // cron/cronJob.js
// const cron = require('node-cron');
// const { generateNewRateForCron } = require('../controllers/rateController'); // Updated import

// // Cron job to run every second
// cron.schedule('* * * * * *', async () => {
//   try {
//     // Call the generateNewRateForCron function to create a new rate based on the last stored rates
//     await generateNewRateForCron();

//     console.log('New rate generated by cron job using last stored rates');
//   } catch (error) {
//     console.error('Error in cron job:', error);
//   }
// });

// console.log('Cron job is running every second...');

// module.exports = cron;
